name: Tests

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened] # Default
  push:
    branches:
      - main

jobs:
  tests:
    name: run feature tests
    runs-on: sfdc-ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install CumulusCI
        run: |
          python -m pip install -U pip
          python -m pip install cumulusci
      - uses: actions/setup-node@v2
      - run: npm install yarn
      - run: yarn
      - run: yarn test
