name: Feature Test

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  tests:
    name: run tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - run: npm install yarn
      - run: yarn test
