name: Tests

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  tests:
    name: run feature tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install CumulusCI
        run: |
          python -m pip install -U pip
          python -m pip install cumulusci
      - uses: actions/setup-node@v2
      - run: npm install yarn
      - run: yarn test
