name: Release

on:
    push:
        branches:
            - main
        path:
            - version.txt

jobs:
    build_release:
        runs-on: macos-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2
            - name: setup node
              uses: actions/setup-node@v2
            - name: install Visual Studio Code Extensions
              run: |
                  npm install -g yarn
                  npm install -g vsce
                  yarn
            - name: version
              run: echo "::set-output name=version::$(cat version.txt)"
              id: version
            - name: package extension
              run: vsce package ${{ steps.version.outputs.version }}
            - name: create release
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              uses: actions/create-release@v1
              id: create_release
              with:
                  draft: false
                  prerelease: false
                  release_name: v${{ steps.version.outputs.version }}
                  tag_name: v${{ steps.version.outputs.version }}
                  body_path: CHANGELOG.md
            - name: upload extension binary
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url}}
                  asset_path: cci-${{ steps.version.outputs.version }}.vsix
                  asset_name: cci-${{ steps.version.outputs.version }}.vsix
                  asset_content_type: application/binary
